@baseUrl = http://localhost:3000
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY4NDhlN2U1ZWY5NWNmOGMxYzFmNzMiLCJpYXQiOjE3MTMxNzI3MjUsImV4cCI6MTcxMzE3NjMyNX0.GP0VSyjSLu0o1a16x3qmYxX4NI8MlPkWeTZ8UbHRoNA

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "kevin",
    "password": "1234"
}

###
GET {{baseUrl}}/auth/checkToken
Authorization: bearer {{authToken}}