@baseUrl = http://localhost:3000/closets/

#===================== CREATE =====================#

###
POST {{baseUrl}}
Content-Type: application/json

[
    {
        "name": "INF-A01-ARM1",
        "room": "A01"
    },
    {
        "name": "INF-A01-ARM2",
        "room": "A01"
    },
    {
        "name": "INF-A01-ARM3",
        "room": "A01"
    },
    {
        "name": "INF-A01-ARM4",
        "room": "A01"
    }
]

#===================== READ =====================#

###
GET {{baseUrl}}10

###
GET {{baseUrl}}
Content-Type: application/json

[
    "66260104884f0934fcbace85",
    "66260104884f0934fcbace84"
]

#===================== UPDATE =====================#

###
PATCH {{baseUrl}}
Content-Type: application/json

[
    {
        "id": "66260104884f0934fcbace85",
        "name" : "INF-B01-ARM9"
    },
    {
        "id": "66260104884f0934fcbace84",
        "name" : "INF-B05-ARM8",
        "room": "B05"
    }
]

#===================== DELETE =====================#

###
DELETE {{baseUrl}}66260104884f0934fcbace84