@baseUrl = http://localhost:3000/items/

#===================== CREATE =====================#

###
POST {{baseUrl}}insertOne
Content-Type: application/json

{
    "description": "Macbook",
    "quantity": 17,
    "category": "Ordinateur Portable",
    "closet": "INF-B01-ARM2"
}

###
POST {{baseUrl}}insertMany
Content-Type: application/json

[
    {
        "description": "Macbook air",
        "quantity": 13,
        "category": "Ordinateur",
        "closet": "INF-B01-ARM4"
    },
    {
        "description": "Câble Display Port",
        "quantity": 54,
        "category": "Câble",
        "closet": "INF-B01-ARM2"
    }
]

#===================== READ =====================#

###
GET {{baseUrl}}20

###
GET {{baseUrl}}selectOne/66014ec1622e724ee1249e6c

###
GET {{baseUrl}}selectMany
Content-Type: application/json

[
    "66014ec1622e724ee1249e6c",
    "6601778edcd7193effce0093"
]

#===================== UPDATE =====================#

###
PATCH {{baseUrl}}updateOne
Content-Type: application/json

{
    "id": "66014ec1622e724ee1249e6c",
    "quantity": 7
}

###
PATCH {{baseUrl}}updateMany
Content-Type: application/json

[
    {
        "id": "66014ec1622e724ee1249e6c",
        "quantity": 5
    },
    {
        "id": "6601778edcd7193effce0093",
        "quantity": 3,
        "closet": "hello"
    }
]

#===================== DELETE =====================#

###
DELETE {{baseUrl}}deleteOne/661cd096c4f5367a85e924c6

###
DELETE {{baseUrl}}deleteMany
Content-Type: application/json

[
    "661cd283179c1263ce52dbef",
    "661cd28a179c1263ce52dbf1"
]