@baseUrl = http://localhost:3000/items/

#===================== CREATE =====================#

###
POST {{baseUrl}}
Content-Type: application/json

[
    {
        "description": "Macbook air",
        "quantity": 13,
        "category": "Ordinateur",
        "closet": "INF-A01-ARM1"
    },
    {
        "description": "Câble Display Port",
        "quantity": 54,
        "category": "Câble",
        "closet": "INF-A01-ARM1"
    },
    {
        "description": "Tablette",
        "quantity": 4,
        "category": "tablette",
        "closet": "INF-A01-ARM1"
    },
    {
        "description": "Post-it",
        "quantity": 205,
        "category": "papeterie",
        "closet": "INF-A01-ARM1"
    }
]

#===================== READ =====================#

###
GET {{baseUrl}}20-quantity-ascending-none-none-

###
GET {{baseUrl}}
Content-Type: application/json

[
    "6625ff9ecc1102663e38ac99",
    "6625ff9ecc1102663e38ac9b"
]

#===================== UPDATE =====================#

###
PATCH {{baseUrl}}
Content-Type: application/json

[
    {
        "id": "6625ff9ecc1102663e38ac99",
        "quantity": 5,
        "closet": "INF-B01-ARM1"
    },
    {
        "id": "6625ff9ecc1102663e38ac9b",
        "quantity": 50
    }
]

#===================== DELETE =====================#

###
DELETE {{baseUrl}}
Content-Type: application/json

[
    "6625ff9ecc1102663e38ac99",
    "6625ff9ecc1102663e38ac9b"
]