@baseUrl = http://localhost:3000/items

#===================== CREATE =====================#

###
POST {{baseUrl}}
Content-Type: application/json

{
    "description": "Ecran 27\"",
    "quantity": 4,
    "fk_category": 2,
    "fk_closet": 1
}

#===================== READ =====================#

###
POST {{baseUrl}}/options
Content-Type: application/json

{
    "sort": "closet",
    "order": "desc"
}

###
GET {{baseUrl}}/2

#===================== UPDATE =====================#

###
PATCH {{baseUrl}}
Content-Type: application/json

{
    "id": 2,
    "description": "PC windows 10",
    "quantity": 5,
    "fk_category": 3,
    "fk_closet": 7
}

#===================== DELETE =====================#

###
DELETE {{baseUrl}}/1