@baseUrl = http://localhost:3000
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY4NDhlN2U1ZWY5NWNmOGMxYzFmNzMiLCJpYXQiOjE3MTEzNzE3MjksImV4cCI6MTcxMTM3NTMyOX0.g3rp7MF6JzeySY8ofhh-xlnCu0mXVILI8qLJRPWPwh0

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "kevin",
    "password": "1234"
}

###
GET {{baseUrl}}/auth/checkToken
Authorization: bearer {{authToken}}

###
POST {{baseUrl}}/closets/insertOne
Content-Type: application/json

{
    "closet": "INF-B01-ARM5",
    "room": "B01"
}

###
POST {{baseUrl}}/items/insertOne
Content-Type: application/json

{
    "description": "Souris",
    "quantity": 10,
    "category": "périphérique",
    "closet": "INF-B01-ARM10"
}

###
POST {{baseUrl}}/items/insertMany
Content-Type: application/json

[
    {
        "description": "Macbook",
        "quantity": 13,
        "category": "Ordinateur",
        "closet": "INF-B01-ARM1"
    },
    {
        "description": "Câble HDMI",
        "quantity": 54,
        "category": "Câble",
        "closet": "INF-B01-ARM1"
    },
    {
        "description": "Test",
        "quantity": 5,
        "closet": "INF-B01-ARM1"
    }
]