@baseUrl = http://localhost:3000/auth 
@authToken = 

###
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "MyUser", 
    "password": "12345"
}

### 
POST {{baseUrl}}/login 
Content-Type: application/json

{
    "username": "kevin", "password": "1234"
}

### GET {{baseUrl}}/auth/checkToken Authorization: bearer {{authToken}}
