@baseUrl = http://localhost:3000/closets

#===================== CREATE =====================#

###
POST {{baseUrl}}
Content-Type: application/json

[
    {
        "name": "INF-B01-ARM11",
        "room": "B01"
    },
    {
        "name": "INF-B01-ARM12",
        "room": "B01"
    }
]

#===================== READ =====================#

###
GET {{baseUrl}}/limit/50

###
GET {{baseUrl}}/66018c3dd4e7a69da37b293f

#===================== UPDATE =====================#

###
PATCH {{baseUrl}}
Content-Type: application/json

[
    {
        "_id": "662909f970ebf77d373cf8b1",
        "room": "A03dd"
    },
    {
        "_id": "662909f970ebf77d373cf8b2",
        "room": "A05"
    }
]

#===================== DELETE =====================#

###
DELETE {{baseUrl}}/662909f970ebf77d373cf8b2